### ISSUE TITLE
Parsing QueryStrings from imput url. 

### ISSUE THREAD

**Issue by pylover** [Carrene/bddrest#9]
##### Given: 

```python
given(url='/path/res?a=1')
```

##### Result
```yaml
url: /path/res
query:
  a: 1
```
